language: java
jdk:
  - oraclejdk11

before_install:
  - docker run -p7474:7474 -p7687:7687 -e NEO4J_AUTH=neo4j/s3cr3t neo4j
  - sudo systemctl status neo4j

script:
  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install
