language: java
jdk:
  - oraclejdk11

before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install neo4j

services:
  - neo4j

script:
  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install
