language: java
jdk:
  - oraclejdk11

before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update
  - "wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -"
  - echo 'deb https://debian.neo4j.com stable latest' | sudo tee /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install -y cypher-shell neo4j
  - sudo systemctl enable neo4j
  - sudo systemctl start neo4j
  - sudo systemctl status neo4j

script:
  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install
