language: java
jdk:
  - oraclejdk11

before_install:
  - sudo add-apt-repository universe
  - sudo apt install apt-transport-https ca-certificates curl software-properties-common
  - "curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -"
  - sudo add-apt-repository "deb https://debian.neo4j.com stable 4.1"
  - sudo apt-get update
  - sudo apt-get install neo4j
  - sudo systemctl enable neo4j.service
  - sudo systemctl start neo4j
  - sudo systemctl status neo4j.service

script:
  - mvn -e -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install
